import { COMMON_PHRASES } from '../constants/commonPhrases.js';

export const explainSentences = {
  // Section headers and static text (now always full sentences)
  header: () => COMMON_PHRASES.header,
  detailsHeader: () => COMMON_PHRASES.detailsHeader,
  summaryHeader: () => COMMON_PHRASES.summaryHeader,
  commandType: () => COMMON_PHRASES.commandRelatedOptions.type,
  commandCategory: () => COMMON_PHRASES.commandRelatedOptions.category,
  commandPurpose: () => COMMON_PHRASES.commandRelatedOptions.purpose,
  commandInputs: () => COMMON_PHRASES.commandRelatedOptions.inputs,
  commandOutputs: () => COMMON_PHRASES.commandRelatedOptions.outputs,
  commandFlags: () => COMMON_PHRASES.commandRelatedOptions.flags,
  commandOptions: () => COMMON_PHRASES.commandRelatedOptions.options,
  commandPerformance: () => COMMON_PHRASES.commandRelatedOptions.performance,
  commandSecurity: () => COMMON_PHRASES.commandRelatedOptions.security,
  commandDependencies: () => COMMON_PHRASES.commandRelatedOptions.dependencies,
  commandSideEffects: () => COMMON_PHRASES.commandRelatedOptions.sideEffects,
  commandWarnings: () => COMMON_PHRASES.commandRelatedOptions.warnings,
  commandLimitations: () => COMMON_PHRASES.commandRelatedOptions.limitations,
  commandExamples: () => COMMON_PHRASES.commandRelatedOptions.examples,
  commandDocs: () => COMMON_PHRASES.commandRelatedOptions.docs,
  commandAuthor: () => COMMON_PHRASES.commandRelatedOptions.author,
  commandVersion: () => COMMON_PHRASES.commandRelatedOptions.version,
  commandLastModified: () => COMMON_PHRASES.commandRelatedOptions.lastModified,
  commandRelated: () => COMMON_PHRASES.commandRelatedOptions.relatedCommands,
  contextEnrichmentPrefix: () => COMMON_PHRASES.contextEnrichmentPrefix,
  user: () => COMMON_PHRASES.user,
  platform: () => COMMON_PHRASES.platform,
  mode: () => COMMON_PHRASES.mode,
  pluginInfo: (plugin: string) => `This command uses the "${plugin}" plugin.`,
  whatWillHappenHeader: () => COMMON_PHRASES.whatWillHappenHeader,
  whyChoicesHeader: () => COMMON_PHRASES.whyChoicesHeader,
  resultHeader: () => COMMON_PHRASES.resultHeader,
  schemaVersion: (v: string) => `Schema version: ${v}.`,
  exitCode: (code: number) => `The process exited with code ${code}.`,
  confidence: (conf: string) => `Confidence: ${conf}.`,
  whatWillNotHappenHeader: () => COMMON_PHRASES.whatWillNotHappenHeader,
  inputsOutputsHeader: () => COMMON_PHRASES.inputsOutputsHeader,
  effectsHeader: () => COMMON_PHRASES.effectsHeader,
  technicalWorkflowHeader: () => COMMON_PHRASES.technicalWorkflowHeader,
  flagsUsedHeader: () => COMMON_PHRASES.flagsUsedHeader,
  errorsHeader: () => COMMON_PHRASES.errorsHeader,
  warningsHeader: () => COMMON_PHRASES.warningsHeader,
  technicalDetailsHeader: () => COMMON_PHRASES.technicalDetailsHeader,
  environmentHeader: () => COMMON_PHRASES.environmentHeader,
  // Dynamic effect phrases (always return full sentences)
  inputRead: (context: any) => COMMON_PHRASES.inputRead({ context }),
  outputWrite: (context: any) => COMMON_PHRASES.outputWrite({ context }),
  noNetwork: () => COMMON_PHRASES.noNetwork(),
  noOriginalModification: () => COMMON_PHRASES.noOriginalModification(),
  dataLocalOnly: () => COMMON_PHRASES.dataLocalOnly(),
  noBackgroundTasks: () => COMMON_PHRASES.noBackgroundTasks(),
  externalTool: (context: any) => COMMON_PHRASES.externalTool({ context }),
  dimensionsChange: (context: any) => COMMON_PHRASES.dimensionsChange({ context }),
  formatConversion: (context: any) => COMMON_PHRASES.formatConversion({ context }),
  qualityChange: (context: any) => COMMON_PHRASES.qualityChange({ context }),
  metadataPreserved: () => COMMON_PHRASES.metadataPreserved(),
  audioProcessing: (context: any) => COMMON_PHRASES.audioProcessing({ context }),
  videoProcessing: (context: any) => COMMON_PHRASES.videoProcessing({ context }),
  documentProcessing: (context: any) => COMMON_PHRASES.documentProcessing({ context }),
  streamProcessing: (context: any) => COMMON_PHRASES.streamProcessing({ context }),
  pipelineExecution: (context: any) => COMMON_PHRASES.pipelineExecution({ context }),
  pluginAction: (context: any) => COMMON_PHRASES.pluginAction({ context }),
  detectedInputFiles: (context: any) => COMMON_PHRASES.detectedInputFiles ? COMMON_PHRASES.detectedInputFiles({ context }) : '',
  detectedOutputFiles: (context: any) => COMMON_PHRASES.detectedOutputFiles ? COMMON_PHRASES.detectedOutputFiles({ context }) : '',
  errorHandling: () => COMMON_PHRASES.errorHandling(),
  validation: () => COMMON_PHRASES.validation(),
  outputPreview: () => COMMON_PHRASES.outputPreview(),
  logging: () => COMMON_PHRASES.logging(),
  cleanup: () => COMMON_PHRASES.cleanup(),
  // Summary and warnings (full sentences)
  summarySuccess: () => COMMON_PHRASES.summarySuccess,
  summaryFailure: () => COMMON_PHRASES.summaryFailure,
  summaryPartial: () => COMMON_PHRASES.summaryPartial,
  warningDeprecated: (flag: string) => COMMON_PHRASES.warningDeprecated(flag),
  warningIgnored: (flag: string) => COMMON_PHRASES.warningIgnored(flag),
  // Explain-only summaries and warnings
  explainOnlySummary: () => COMMON_PHRASES.explainOnlySummary,
  explainOnlySummaryWithWarnings: () => COMMON_PHRASES.explainOnlySummaryWithWarnings,
  explainOnlySummaryWithErrors: () => COMMON_PHRASES.explainOnlySummaryWithErrors,
  // Tips (full sentences)
  tipDetails: () => COMMON_PHRASES.tipDetails,
  tipJson: () => COMMON_PHRASES.tipJson,
  tipHuman: () => COMMON_PHRASES.tipHuman,
};